[workspace]
channels = ["conda-forge"]
name = "stagebridge"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
python = "3.12.*"
nicegui = ">=3.8.0,<4"
numpy = ">=2.4.2,<3"
